services:
  db:
    image: postgres:16
    container_name: postgres_vote_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: votedb
    ports:
      - "5434:5432"
    volumes:
      - pgdata_vote:/var/lib/postgresql/data
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db
    networks:
      - app-net

  vote-service:
    build: .
    container_name: voting_vote_service
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/votedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
      SERVER_PORT: 8082
      restart: always
    networks:
      - app-net

volumes:
  pgdata_vote:

networks:
  app-net:
    external: true